### PR TITLE
Remove google login

### PR DESCRIPTION
**Pull request by jasondsouza35**
## Notion ticket link

[Ticket Name](https://www.notion.so/uwblueprintexecs/Remove-Google-Login-2381bf2299c14678b364abd900965ddd)

## Implementation description
* We shouldn’t have the “Login with Google” button on the login page anymore or any other instances of the Google login in general.

## Steps to test
1. Make sure the localhost website has no places with a "Log in with Google" type option.
2. If you want, check the branch to ensure there aren't any instances that refer to logging in with Google.

## What should reviewers focus on?
* Make sure you can't log in with Google doesn't exist as an option.

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Review by carolynzhang18 — COMMENTED** [review]
Lookin pretty good!! Two comments:
1. In `firebaseRestClient.ts`, there's a `signInWithGoogleOAuth` that we can probably remove too.
2. `type SignupMethod = "PASSWORD"` in `authTypes.ts` is kind of redundant now, since we don't need to differentiate between two different types of logins. I think we should be able to get rid of all `SignupMethod` references?
(EDIT) 2.5. `createUser` in `userService.ts` now has an excess `authId` param that can be removed too

Should be quick fixes, hopefully :)

**Review by ji-mmyliu — CHANGES_REQUESTED** [review]
Looks great! I saw a few more OAuth-related sections that can probably be removed. If you search "OAuth" in the entire repo, there's a few more (except the ones related to `nodemailer`, which we'll still need).

image

**Review by carolynzhang18 — APPROVED** [review]
NICE!!! Tysm for doing this ticket, it's nice not getting that "Script error" anymore 🫶

**Review by ji-mmyliu — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
