### PR TITLE
Create the status user attribute and enable timestamps

### PR DESCRIPTION
**Pull request by ji-mmyliu**
## Notion ticket link

[User Status](https://www.notion.so/uwblueprintexecs/User-Status-809f2f44a1744d23b724ed590f09c379)

## Implementation description
* Created a `Status` type enum and updated user schema
* Enabled timestamps on User schema

## Steps to test
1. Ensure new users are created with `createdAt`, `updatedAt`, and `status` attributes in the database

## What should reviewers focus on?
* Style of code and behaviour of code in manipulating database

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Review by harishan-r — APPROVED** [review]
Lgtm! I also tested it and the entries in MongoDB now include the new fields

**Review by carolynzhang18 — COMMENTED** [review]
all the schema stuff is lookin good! 😎

pretty much all the comments are about `status: "Active"` ... which I realize is totally my fault for saying "oh just hardcode everything to Active" in the ticket - sorry!! I didn't realize so many of the instances would have a predictable value we could drop in there, my bad!! hope it's not too much work!

**Comment by ji-mmyliu** [comment]
> pretty much all the comments are about `status: "Active"` ... which I realize is totally my fault for saying "oh just hardcode everything to Active" in the ticket - sorry!! I didn't realize so many of the instances would already have a predictable value we could drop in there, my bad!! I pointed out all of these in the comments - hope it's not too much work!

Yea I don't know why I didn't think of that myself! :facepalm:

**Review by 98ZhaoJeffrey — APPROVED** [review]
poggers

**Review by carolynzhang18 — APPROVED** [review]

**Pull request merged**
