### PR TITLE
added new route for forgot password page

### PR DESCRIPTION
**Pull request by jasondsouza35**
## Notion ticket link

[Ticket Name](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)

## Implementation description
* 

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Review by carolynzhang18 — COMMENTED** [review]
page route looks good! this ticket also involves adding styling for the page (based on the figma design):
image
could you do that as well? 🧑‍💻

**Comment by carolynzhang18** [comment]
ooh you probably need to run a `git pull origin main` - I don't think the theming stuff is even in your branch D:

**Comment by carolynzhang18** [comment]
if this is a duplicate of #73 , are we good to close this one?

**Comment by jasondsouza35** [comment]
> if this covered by #73 , are we good to close this one?

ya, that's my bad, I'm gonna close this

**Pull request closed without merging**
